# Generated by Django 3.2 on 2021-10-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authir',
            new_name='author',
        ),
    ]
