# Generated by Django 3.2 on 2021-10-30 16:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20211030_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='mini_text',
            field=ckeditor.fields.RichTextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contactlink',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Контактные данные'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Социальная сеть'),
        ),
    ]
