# Generated by Django 3.2 on 2021-11-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20211103_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='phone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
